# Generated by Django 2.1.2 on 2018-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20181012_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.AddField(
            model_name='contract',
            name='asset_model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='asset_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
